### ISSUE TITLE
What is the advantage of using this over safari shared credentials?

### ISSUE THREAD

**Issue by rsaunders100** [mackuba/SafariAutoLoginTest#2]
Seems to do the same thing as shared credentials i.e. if you have logged in on Safari you get logged in on the app.
https://developer.apple.com/library/ios/documentation/Security/Reference/SharedWebCredentialsRef/

Shared credentials also has the advantage of working the other way, i.e. if you sign in on the app you will be signed in on Safari.

Also apple are pushing away from custom URL schemes in favour of universal links.

**Comment by bnickel** [comment]
Can SharedWebCredentials be used for anything other than username/password field? If, for example, your website uses Google or Facebook for login, it looks like you can't use SharedWebCredentials.  With this you could actually transfer a live session from Safari to an app.

Of course, URL schemes do present as big a risk as ever, with the possibility of a third-party app using the same scheme in order to steal sessions.  I've not seen how SafariViewController handles universal links but if they trigger an NSUserActivity continuation, a secure flow could be to show the web page, have it navigate to a universal link, and that link continue in the app.

**Comment by mackuba** [comment]
Looks like Safari shared credentials require iCloud Keychain, right? I don't know what's the % of users that use it, but I'm assuming it's definitely not 100%. E.g. most of users who previously used 1Password (like me) probably keep using it and didn't switch.

As for universal links - yeah, I forgot to mention this in the readme, you could just as well make the index.html redirect to a universal link instead of a custom URL scheme. (I'm guessing, I haven't actually tried.)

**Comment by fabb** [comment]
An interesting replacement in iOS 11 will be `SFAuthenticationSession`

**Comment by mackuba** [comment]
@fabb thanks for the suggestion, I've experimented with it a bit right now and it seems to work pretty well, so I've added a new "Authenticate" button to the app that launches a `SFAuthenticationSession` 👍

**Comment by mackuba** [comment]
I've also mentioned Shared Web Credentials as a possible alternative in the readme. And universal links :)
